name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, rc, stable)"
        required: true
        default: "rc"
      skip-version-rc:
        description: "release RC version just with lerna publish, skip run lerna version(yes or no)"
        required: false
        default: "no"
      skip-sync-version-pkg:
        description: "skip sync up target pkg version. input templates to skip sync up version with sdk; fx-core to skip sync up with simpleauth"
        required: false
        default: ""
  schedule:
    - cron: "0 8 * * *"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Validate CD branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/hotfix/') && github.ref != 'refs/heads/dev' }}
        run: |
          echo It's not allowed to run CD on other branch except main and dev.
          exit 1

      - name: Validate inputs for main or hotfix
        if: ${{ github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')) && github.event.inputs.preid != 'rc' && github.event.inputs.preid != 'stable' }}
        run: |
          echo It's not allowed to release alpha on main branch.
          exit 1

      - name: Valiadte inputs for dev
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev' && github.event.inputs.preid != 'alpha' }}
        run: |
          echo It's not allowed to release RC or stable on dev branch.
          exit 1

      - name: Validate schedule
        if: ${{ github.event_name == 'schedule' && github.ref != 'refs/heads/dev' }}
        run: |
          echo It's not allowed to run schedule release except dev branch.
          exit 1

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'MSFT-yiz'
          git config --global user.email 'yiz@microsoft.com'

      - name: release alpha npm packages to npmjs.org
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev' && github.event.inputs.preid == 'alpha')}}
        run: |
          npx lerna version prerelease --preid=alpha.$(git rev-parse --short HEAD) --exact --no-push --allow-branch dev --yes

      - name: version rc npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' && github.ref == 'refs/heads/main' && github.event.inputs.skip-version-rc == 'no'}}
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=rc --no-changelog --ignore-scripts --yes
        env:
          SkipSyncup: ${{ github.event.inputs.skip-sync-version-pkg }}

      - name: version rc npm packages to npmjs.org on hotfix
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' && startsWith(github.ref, 'refs/heads/hotfix/') && github.event.inputs.skip-version-rc == 'no'}}
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=rc-hotfix --no-changelog --allow-branch ${GITHUB_REF#refs/*/} --ignore-scripts --yes
        env:
          SkipSyncup: ${{ github.event.inputs.skip-sync-version-pkg }}

      - name: version stable npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')) && github.event.inputs.preid == 'stable' }}
        run: |
          npx lerna version --conventional-commits --conventional-graduate --no-changelog --allow-branch ${GITHUB_REF#refs/*/} --yes
        env:
          SkipSyncup: ${{ github.event.inputs.skip-sync-version-pkg }}

      - name: version change
        id: version-change
        run: |
          echo "::set-output name=CHANGED::$(git tag --points-at HEAD | xargs)"
          echo "::set-output name=TEMPLATE_VERSION::$(git tag --points-at HEAD | grep templates)"
          echo "::set-output name=EXTENSION_VERSION_NUM::$(git tag --points-at HEAD | grep ms-teams-vscode-extension@ | cut -d '@' -f2)"
          echo "::set-output name=EXTENSION_VERSION::$(git tag --points-at HEAD | grep ms-teams-vscode-extension@)"
          echo "::set-output name=SIMPLEAUTH_VERSION::$(git tag --points-at HEAD | grep simpleauth)"
          echo "::set-output name=SIMPLEAUTH_VERSION_NUM::$(git tag --points-at HEAD| grep simpleauth| cut -d '@' -f2)"
          if git tag --points-at HEAD | grep templates | grep rc;
          then
              git push -d origin $(git tag --points-at HEAD | grep templates | grep rc)
          fi
      
      - name: generate templates
        run: |
          curl -sSL https://git.io/get-mo -o mo && chmod +x mo && sudo mv mo /usr/local/bin/
          .github/scripts/template-zip-autogen.sh

      - name: update tag
        uses: richardsimko/update-tag@v1
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'alpha') }}
        with:
          tag_name: "templates@0.0.0-alpha"
        env:
          GITHUB_TOKEN: ${{ secrets.CD_PAT }}

      - name: release templates' alpha version to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'alpha') }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          prerelease: true
          tag: "templates@0.0.0-alpha"
          artifacts: ./*.zip
          allowUpdates: true
      
      - name: update tag
        uses: richardsimko/update-tag@v1
        if: ${{ (contains(steps.version-change.outputs.CHANGED, 'templates@') || contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx')) && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        with:
          tag_name: "templates@0.0.0-rc"
        env:
          GITHUB_TOKEN: ${{ secrets.CD_PAT }}

      - name: release templates' RC version to github
        if: ${{ (contains(steps.version-change.outputs.CHANGED, 'templates@') || contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx')) && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          prerelease: true
          tag: "templates@0.0.0-rc"
          artifacts: ./*.zip
          allowUpdates: true

      - name: Create Templates Stable Release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: ./*.zip
          name: 'Release for ${{ steps.version-change.outputs.TEMPLATE_VERSION }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version-change.outputs.TEMPLATE_VERSION }}
          allowUpdates: true

      - name: Generate Tag List
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: git tag | grep templates@ > ./template-tags.txt

      - name: Update Template Tag list Release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: ./template-tags.txt
          name: 'Template Tag List'
          body: 'Release to maintain template tag list.'
          token: ${{ secrets.github_token }}
          tag: 'template-tag-list'
          allowUpdates: true  
    
      - name: cleanup templates
        run: rm -rf ./*.zip && git clean -df

      - name: trigger simpleauth azure build pipeline for stable release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'simpleauth') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/mseng/VSIoT'
          azure-pipeline-name: 'Build Simple Auth Release Artifacts' 
          azure-devops-token: '${{ secrets.ADO_PAT }}'
      
      - name: check build status and download assets for stable release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'simpleauth') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: |
          output=$(./.github/scripts/simpleauth-azdo-pipelines.sh ${{ secrets.ADO_PAT }} 11303 >&1)
          echo $output
          asset_id=$(echo $output | rev |cut -d ' ' -f 1 | rev)
          curl "https://dev.azure.com/mseng/_apis/resources/Containers/$asset_id/drop?itemPath=drop/Microsoft.TeamsFx.SimpleAuth_${{ steps.version-change.outputs.SIMPLEAUTH_VERSION_NUM }}.zip" -L -O -u :${{ secrets.ADO_PAT }}
          if [ ! -f Microsoft.TeamsFx.*.zip ]; then exit 1; fi
      
      - name: build SimpleAuth on prerelease
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'simpleauth') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && github.event.inputs.preid != 'stable') }}
        run: |
          dotnet build --configuration Release
          zip -r -j ../../Microsoft.TeamsFx.SimpleAuth_${{ steps.version-change.outputs.SIMPLEAUTH_VERSION_NUM }}.zip src/TeamsFxSimpleAuth/bin/Release/*
        working-directory: ./packages/simpleauth  

      - name: download simpleauth to fx-core
        uses: nick-invision/retry@v2
        with: 
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            if [ -f Microsoft.TeamsFx.SimpleAuth_*.zip ]; then
              cp Microsoft.TeamsFx.SimpleAuth_*.zip packages/fx-core/templates/plugins/resource/simpleauth/SimpleAuth.zip
            else
              ./.github/scripts/downloadSimpleAuth.ps1
            fi
      - name: publish alpha simpleauth to github release page
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'simpleauth') && github.ref == 'refs/heads/dev' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: 'simpleauth-${{steps.version-change.outputs.SIMPLEAUTH_VERSION_NUM}}'
          artifacts: Microsoft.TeamsFx.SimpleAuth_*.zip

      - name: publish simpleauth to github release page
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'simpleauth') && github.ref == 'refs/heads/main'}}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: ${{ steps.version-change.outputs.SIMPLEAUTH_VERSION }}
          artifacts: Microsoft.TeamsFx.SimpleAuth_*.zip

      - name: publish alpha release to npm org
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev' && github.event.inputs.preid == 'alpha')}}
        run: |
          npx lerna publish from-package --dist-tag=alpha --yes --allow-branch dev

      - name: sync up templates deps with sdk version for RC
        if: ${{ contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx') && !contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.event.inputs.preid == 'rc' }}
        run: |
          node sdk-sync-up-version.js
        working-directory: ./.github/scripts

      - name: update cli ai key
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.preid == 'stable'||github.event.inputs.preid == 'rc') }}
        uses: jossef/action-set-json-field@v1
        with:
          file: ./packages/cli/package.json
          field: aiKey
          value: ${{ secrets.CLI_PUBLIC_AIKEY }}

      - name: update extension ai key
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.preid == 'stable' || github.event.inputs.preid == 'rc') }}
        uses: jossef/action-set-json-field@v1
        with:
          file: ./packages/vscode-extension/package.json
          field: aiKey
          value: ${{ secrets.EXT_PUBLIC_AIKEY }}
      
      - name: commit change on local
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.preid == 'stable' || github.event.inputs.preid == 'rc') }}
        run: |
          git add .
          git commit -m "chore: update ai key"

      - name: publish rc npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        run: |
          npx lerna publish from-package --dist-tag=rc --yes

      - name: publish stable npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: |
          npx lerna publish from-package --yes

      - name: pack vsix
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            sleep 20
            cd ./packages/vscode-extension
            npm install --only=production
            npx vsce package

      - name: release daily VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && github.ref == 'refs/heads/dev'  }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: 'vscode-extension-${{ steps.version-change.outputs.EXTENSION_VERSION_NUM }}'
          artifacts: ./packages/**/*.vsix
          prerelease: true

      - name: release RC VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && contains(steps.version-change.outputs.CHANGED, 'rc') }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: ${{ steps.version-change.outputs.EXTENSION_VERSION }}
          artifacts: ./packages/**/*.vsix
          prerelease: true
      
      - name: release stable VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && !contains(steps.version-change.outputs.CHANGED, 'rc') && github.ref == 'refs/heads/main' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: ${{ steps.version-change.outputs.EXTENSION_VERSION }}
          artifacts: ./packages/**/*.vsix